#!/usr/bin/env bash
# Regenerates CODE_INDEX.md for the current project.
# Run by PostToolUse hook after Edit/Write, or manually.
set -euo pipefail

ROOT="${CLAUDE_PROJECT_ROOT:-$(pwd)}"
OUTPUT="$ROOT/CODE_INDEX.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

index_js() {
  local f="$1"
  local lines
  lines=$(wc -l < "$f")
  echo "## $(basename "$f") ($lines lines)"
  awk '
    BEGIN { cnt = 0 }
    /^[[:space:]]*(export[[:space:]]+)?(async[[:space:]]+)?function[[:space:]]+[A-Za-z_$][A-Za-z0-9_$]*[[:space:]]*\(/ {
      n = split($0, a, /function[[:space:]]+/)
      name = a[2]
      sub(/[[:space:]]*\(.*/, "", name)
      if (name != "") { names[cnt] = name; lnums[cnt] = NR; cnt++ }
    }
    /^[[:space:]]*(export[[:space:]]+)?(const|let|var)[[:space:]]+[A-Za-z_$][A-Za-z0-9_$]*[[:space:]]*=[[:space:]]*(async[[:space:]]*)?(function[[:space:]]*\(|\()/ {
      n = split($0, a, /(const|let|var)[[:space:]]+/)
      name = a[2]
      sub(/[[:space:]]*=.*/, "", name)
      if (name != "") { names[cnt] = name; lnums[cnt] = NR; cnt++ }
    }
    END {
      for (i = 0; i < cnt; i++) {
        lim = (i+1 < cnt) ? lnums[i+1] - lnums[i] : NR - lnums[i] + 1
        printf "- `%s` \xe2\x86\x92 L%d limit=%d\n", names[i], lnums[i], lim
      }
    }
  ' "$f"
  echo ""
}

index_md() {
  local f="$1"
  local rel="${f#$ROOT/}"
  local lines
  lines=$(wc -l < "$f")
  echo "## $rel ($lines lines)"
  awk '/^#{1,4}[[:space:]]/ { printf "- `%s` \xe2\x86\x92 L%d\n", $0, NR }' "$f"
  echo ""
}

{
  printf '# CODE_INDEX.md\n'
  printf '> Auto-generated by code-index-md. Do not edit manually.\n'
  printf '> Updated: %s\n' "$TIMESTAMP"
  printf '> Usage: find symbol \xe2\x86\x92 line number \xe2\x86\x92 `Read file offset=N limit=L` (L shown per function)\n'
  printf '\n'

  # JS files in project root — skip minified and vendor
  for f in "$ROOT"/*.js; do
    [[ -f "$f" ]] || continue
    [[ "$f" == *.min.js ]] && continue
    basename "$f" | grep -qiE '^d3' && continue
    index_js "$f"
  done

  # MD files up to 3 levels deep — skip self and vendor dirs
  while IFS= read -r -d '' f; do
    [[ "$f" == "$OUTPUT" ]] && continue
    index_md "$f"
  done < <(find "$ROOT" -maxdepth 3 -name "*.md" \
    -not -path "*/node_modules/*" \
    -not -path "*/.git/*" \
    -not -path "*/d3js/*" \
    -print0 | sort -z)

} > "$OUTPUT"

printf 'CODE_INDEX.md updated (%s)\n' "$TIMESTAMP" >&2
